### PR TITLE
improve feature

### PR DESCRIPTION
**Pull request by arnaudon**
Improve .feature and added missing Path

In relation to this PR https://github.com/BlueBrain/NeuroM/pull/874, the feature dataset now looks like:

```  
       | properties         | axon                  | all                   | neuron
       | name     |  mtype  | feature_1 | feature_2 | feature_1 | feature_2 | feature_3
   -------------------------------------------------------------------------------------
    0  | simple    | L1_DAC | 0.1       | 0.2       | 0.15      | 0.25      | 1000
```

### CODE REVIEW

**Comment by wizmer** [comment]
Can you make a commit message a bit like e994920c3b8c87f4ddfda0dbf31b0739b2721ce9 to have an idea of what's the new dataframe format.

**Comment by wizmer** [comment]
Also, pinging @jdcourcol because I think he uses `extract_dataframe` as well.

**Comment by arnaudon** [comment]
Something like that?

**Comment by wizmer** [comment]
Perfect. Thanks

**Comment by wizmer** [comment]
Sorry, I got confused with the 2 similar PRs. 
@jdcourcol I wanted to ping you about: https://github.com/BlueBrain/NeuroM/pull/874

**Comment by jdcourcol** [comment]
no worries

**Pull request merged**
