### PR TITLE
Assign the correct soma types when they are converted

### PR DESCRIPTION
**Pull request by mgeplf**

### CODE REVIEW

**Comment by mgeplf** [comment]
I'm getting a failure in the `amira` converter, @arnaudon; I think you added that.
How was the `amira_cell.asc` created? I notice that there seems to be duplicated points:
```
(264.572998047 -563.692993164 -238.026992798 1.360000014)
(
  (264.572998047 -563.692993164 -238.026992798 1.360000014)
  (264.572998047 -563.692993164 -238.026992798 1.360000014)
```

**Comment by mgeplf** [comment]
> arg, is it because of MorphIO release? I will check asap

I'm not sure, I'm not aware of anything that changed, but it's possible.  Unfortunately, it's working on my machine, so it's harder to debug.

I was just wondering how the ASC file was made.

**Comment by arnaudon** [comment]
its the issue with latest numpy and argsort that @adrien-berchet  discovered the other day

**Comment by arnaudon** [comment]
it should be fixed now

**Comment by adrien-berchet** [comment]
For Py37, why does it try to build `libsonata` instead of using the wheel? :thinking:

**Comment by eleftherioszisis** [comment]
> For Py37, why does it try to build `libsonata` instead of using the wheel? thinking

We should drop python3.7 altogether as it has reached end-of-life.

**Comment by adrien-berchet** [comment]
> We should drop python3.7 altogether as it has reached end-of-life.

Yes but the question still remains :)

**Comment by eleftherioszisis** [comment]
> > We should drop python3.7 altogether as it has reached end-of-life.
> 
> Yes but the question still remains :)

Yeah, there are no wheels for python3.7 libsonata:
https://pypi.org/project/libsonata

**Comment by adrien-berchet** [comment]
> Yeah, there are no wheels for python3.7 libsonata: https://pypi.org/project/libsonata/#files

Aaaah it's because the metadata of libsonata are wrong... :facepalm: 
The metadata tell pip that `libsonata` is compatible with Py37 but the wheel for it is not available. To fix that we should change the metadata in libsonata and push a Py37 wheel for the last version that is marked as supporting Py37.

**Comment by mgeplf** [comment]
@arnaudon > its the issue with latest numpy and argsort that @adrien-berchet discovered the other day

Nice, thanks for the fix

**Review by adrien-berchet — APPROVED** [review]

**Pull request merged**
