### PR TITLE
Adding banner to README

### PR DESCRIPTION
**Pull request by alex4200**
### Context

Adding a banner to the README in preparation for adding this tool to the morphology suite

### CODE REVIEW

**Comment by mgeplf** [comment]
I'll look at why the CI is failing

**Comment by mgeplf** [comment]
It fails due to not finding the new banner:
```
  Warning, treated as error:
  ../README.rst:322:image file not readable: doc/source/logo/BBP-Morph-Tool.jpg
  make: *** [Makefile:29: html] Error 2
  Error: ERROR: InvocationError for command /usr/bin/make html SPHINXOPTS=-W (exited with code 2)
```

We should probably re-organize the docs, so the landing page has a brief description, and points to the readthedocs for the main documentation.

**Comment by alex4200** [comment]
Locally it did work. And why does the python 3.9 check succeed, but not the other ones?

**Comment by adrien-berchet** [comment]
@alex4200 : The doc is only build with py38.
@mgeplf : what about just changing the `.. include` directive in the `index.rst` file? We could have this for example:
```rst
.. image:: logo/BBP-Morph-Tool.jpg

.. include:: ../../README.rst
    :start-line: 2 

.. toctree::
   :hidden:

   Home <self>
   morphdb
   api
   changelog

```

**Comment by alex4200** [comment]
But still, the error message 

file not readable: doc/source/logo/BBP-Morph-Tool.jpg

does not make sense, as that file does exist!

**Comment by adrien-berchet** [comment]
> But still, the error message
> 
> `file not readable: doc/source/logo/BBP-Morph-Tool.jpg`
> 
> does not make sense, as that file does exist!

The doc is built using tox which changes the working directory. It works for you because you probably don't use tox to build the doc.

**Comment by alex4200** [comment]
But the file is there! See pull-request 96. 

I do not understand why an existing file is not found.

**Comment by adrien-berchet** [comment]
LGTM now. Is it ok for you @mgeplf ?

**Review by mgeplf — APPROVED** [review]

**Comment by mgeplf** [comment]
I had the same changes :)

Nice workaround, thanks for that - didn't know that existed. Cheers.

**Comment by adrien-berchet** [comment]
You're welcome :)

**Comment by mgeplf** [comment]
Thanks @alex4200 and @adrien-berchet

**Pull request merged**
