### PR TITLE
extend neurondb to dataframe for multiple path columns

### PR DESCRIPTION
**Pull request by arnaudon**
Allow to give a dict to neurondb -> dataframe loader to have multiple path columns (for file format, morphology versions, etc...)

### CODE REVIEW

**Comment by arnaudon** [comment]
arg, sorry, I was using gh, but it messed up with what was on my branch, let me do that PR again...

**Comment by wizmer** [comment]
Changing the signature to this function would break this API as it is already used in multiple places. I won't be the way to go.
Why not a different function though ?

**Comment by wizmer** [comment]
But what you want is simply something like:
```python
pd.concat(neurondb_dataframe(neurondb, path) for path in paths)
```
No ?

**Comment by arnaudon** [comment]
ah ok, I can do it on my side then, I thought this could be of the use here, but if people already use it like that no problemo!

**Comment by arnaudon** [comment]
yes, I can do something like that, with a merge, not concat, I want same number of rows, but several columns for paths

**Pull request closed without merging**
